### ISSUE TITLE
期待增加emoji和image，file

### ISSUE THREAD

**Issue by pccai** [WindrunnerMax/DocEditor#1]
现在写md，类似https://www.docusaurus.io/zh-CN/ 
其实常用的功能有了，就可以用起来，功能简单方便；特别是技术类文字，贴个实例代码，加个注意事项之类的，能艾特某个东西。
适当的模板插入和自动排版，就可以用到企业内部知识库。
逐步完善的过程。

**Comment by WindRunnerMax** [comment]
老哥说的挺有道理，会不断加入一些新的插件的，其实现在有很多非常成熟的工具类似于语雀、飞书，我这也就是做着玩🤣

**Comment by okbug** [comment]
> 

这有用到后端数据库吗

**Comment by okbug** [comment]
> 老哥说的挺有道理，会不断加入一些新的插件的，其实现在有很多非常成熟的工具类似于语雀、飞书，我这也就是做着玩🤣

这有用到后端数据库吗？？

**Comment by WindRunnerMax** [comment]
> > 老哥说的挺有道理，会不断加入一些新的插件的，其实现在有很多非常成熟的工具类似于语雀、飞书，我这也就是做着玩🤣
> 
> 这有用到后端数据库吗？？

纯前端，没有数据库
