### ISSUE TITLE
期待增加图片编辑功能

### ISSUE THREAD

**Issue by pgkk** [WindrunnerMax/DocEditor#2]
图片希望能选中时调整大小等

**Comment by WindRunnerMax** [comment]
后边有时间搞搞 🤣

**Comment by pgkk** [comment]
大哥  抽空搞搞呀。目前这样的块编辑器好像没有其他开源的，做完善后你这个就火了。语雀提了一年多开源也没见开源呀

**Comment by WindRunnerMax** [comment]
开源的有很多吧，quill.js draft.js plate.js 那可太多了，我这只是做着玩玩的 🤣

**Comment by WindRunnerMax** [comment]
已经支持选中调整大小，欢迎共建

**Comment by pgkk** [comment]
厉害&nbsp;太帅了 后面我也学习下slate.js&nbsp;


KK
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月7日(星期天) 晚上11:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [WindrunnerMax/DocEditor] 期待增加图片编辑功能 (Issue #2)





 
已经支持选中调整大小，欢迎共建
 
&mdash;
