### ISSUE TITLE
这是目前见过最优秀的开源富文本

### ISSUE THREAD

**Issue by cgq001** [WindrunnerMax/DocEditor#7]
**作者威武，这是我目前见过的 最优秀的开源富文本了**
我们公司 一条产品线，就是靠的富文本，请的大神，做的富文本编辑器，跟你这个相比，相去甚远

**Comment by WindRunnerMax** [comment]
其实我这就是玩具而已 🤣，你可以看看 plate.js blocksuite 这些，都很棒

**Comment by ajaxpost** [comment]
作者很牛
